batch_size: 16
epochs: 30
lr: 2e-4
hier: bottom
channel: 256
n_res_block: 5
n_res_channel: 256
n_out_res_block: 0
n_cond_res_block: 4
dropout: 0.15
exp_id: 2
early_stop_patience: 15
validation_ratio: 0.02