#dataset settings
dataset: celebA
validation_ratio: 0.05
test_ratio: 0.02
img_size: 256
batch_size: 196

VQ-VAE:
  count_low_usage: True
  epochs: 1000
  lr: 0.00025
  beta: 0.25
  kernel_sizes:
    - 5
    - 5
    - 3
  res_layers: 4
  latent_dimension: 128
  num_layers: 3
  code_book_size: 512
  early_stop_patience: 20