#dataset settings
dataset: celebA
validation_ratio: 0.02
test_ratio: 0.01
img_size: 256
batch_size: 128

VQ-VAE:
  version: 2
  experiment_id: 11
  count_low_usage: True
  epochs: 350
  lr: 0.0003
  beta: 0.25
  kernel_sizes:
    - 3
    - 3
    - 3
  res_layers: 3
  latent_dimension: 128
  code_book_size: 512
  early_stop_patience: 20